import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

// Carga de la fuente Montserrat desde Google Fonts
const montserratSans = Montserrat({
  subsets: ["latin"], // Define los subconjuntos de caracteres
  variable: "--font-montserrat-sans", // Variable CSS para aplicar en los estilos
  weight: ["100", "300", "400", "500", "700", "900"], // Opciones de peso disponibles
});

export const metadata: Metadata = {
  title: "Nicolás Rodriguez Grundy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserratSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
